const VERSION='0.011';
const WORDS_URL='./data/words.json';
const SAVE_VERSION=5;
const SAVE_KEY='gestalt_learning_v5';
const LEGACY_KEYS=['de_b1_rpg_progress_v3','deutsch_quest_v002','gestalt_learning_v4'];
const TG_CHUNK_PREFIX='gestalt_save_';
let tg=null, telegramReady=false, words=[];
let voiceList=[];
const state={screen:'dashboard',ankiIndex:0,ankiRevealed:false,sessionCards:[],sessionAnswerLock:false,toastTimer:null};
const navItems=[['dashboard','⌂','Головна'],['words','▣','Слова'],['anki','▤','Картки'],['profile','⚙','Профіль']];
const titles={dashboard:['Головна','Твій спокійний центр вивчення німецької'],words:['Вивчення слів','Додавай, шукай та переглядай свою колекцію'],anki:['Картки Anki','SRS-повторення та озвучка'],profile:['Профіль','Прогрес, налаштування та синхронізація']};

const $=id=>document.getElementById(id);
const safeGet=k=>{try{return localStorage.getItem(k)}catch{return null}};
const safeSet=(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}};
const safeRemove=k=>{try{localStorage.removeItem(k)}catch{}};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const wordKey=w=>String(w?.id||w?.german||'').toLowerCase().trim();
const now=()=>Date.now();
const todayKey=()=>new Date().toISOString().slice(0,10);
const uid=()=>`u-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;

function defaultSave(){return{version:SAVE_VERSION,xp:0,coins:0,streak:0,lastActivity:'',correct:0,errors:0,answers:0,learnedToday:0,dayKey:todayKey(),dailyGoal:20,mastery:{},review:{},customWords:[],settings:{theme:'dark',reducedMotion:false,voiceRate:0.9,voiceName:'auto',autoSpeak:false},playerName:'Wanderer'}}
let save=defaultSave();
function isObj(x){return x&&typeof x==='object'&&!Array.isArray(x)}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function normalizeSave(input){const d=defaultSave();const x=isObj(input)?input:{};const out={...d,...x,settings:{...d.settings,...(isObj(x.settings)?x.settings:{})}};out.version=SAVE_VERSION;out.xp=Math.max(0,Number(out.xp)||0);out.coins=Math.max(0,Number(out.coins)||0);out.streak=Math.max(0,Number(out.streak)||0);out.correct=Math.max(0,Number(out.correct)||0);out.errors=Math.max(0,Number(out.errors)||0);out.answers=Math.max(0,Number(out.answers)||0);out.learnedToday=Math.max(0,Number(out.learnedToday)||0);out.dailyGoal=clamp(Number(out.dailyGoal)||20,5,50);out.mastery=isObj(out.mastery)?out.mastery:{};out.review=isObj(out.review)?out.review:{};out.customWords=Array.isArray(out.customWords)?out.customWords.filter(w=>isObj(w)&&String(w.german||'').trim()&&String(w.ukrainian||'').trim()).slice(0,500):[];out.settings.theme=out.settings.theme==='light'?'light':'dark';out.settings.reducedMotion=Boolean(out.settings.reducedMotion);out.settings.voiceRate=clamp(Number(out.settings.voiceRate)||0.9,0.65,1.15);out.settings.voiceName=String(out.settings.voiceName||'auto');out.settings.autoSpeak=Boolean(out.settings.autoSpeak);if(out.dayKey!==todayKey()){out.dayKey=todayKey();out.learnedToday=0}return out}

function loadLocal(){let raw=null;try{raw=safeGet(SAVE_KEY);if(raw)save=normalizeSave(JSON.parse(raw));else{for(const k of LEGACY_KEYS){const s=safeGet(k);if(s){try{save=normalizeSave(JSON.parse(s));break}catch{}}}}}catch{save=defaultSave()}}
function persistLocal(){safeSet(SAVE_KEY,JSON.stringify(save))}
function dueWords(){const t=now();return mergedWords().filter(w=>(Number(save.review[wordKey(w)]?.dueAt)||0)<=t).sort((a,b)=>(Number(save.review[wordKey(a)]?.dueAt)||0)-(Number(save.review[wordKey(b)]?.dueAt)||0))}
function mastery(w){return clamp(Number(save.mastery[wordKey(w)]||0),0,5)}
function mergedWords(){const map=new Map();for(const w of words)map.set(wordKey(w),w);for(const w of save.customWords)map.set(wordKey(w),w);return Array.from(map.values())}
function recommendedWord(){const due=dueWords();if(due[0])return due[0];return [...mergedWords()].sort((a,b)=>mastery(a)-mastery(b)||Number(a.frequency||9999)-Number(b.frequency||9999))[0]||null}
function reviewDays(quality,level){const ladder=[1,2,4,7,14,30];if(quality<=0)return 1;if(quality===2)return ladder[Math.max(1,Math.min(5,level+1))];if(quality===4)return ladder[Math.max(2,Math.min(5,level+2))];return 30}
function setReview(w,quality){const k=wordKey(w);const current=save.review[k]||{box:0};let box=clamp(Number(current.box)||0,0,5);if(quality<=0)box=0;else if(quality===2)box=clamp(box+1,0,5);else if(quality===4)box=clamp(box+2,0,5);else box=5;save.review[k]={box,dueAt:now()+reviewDays(quality,box)*86400000,lastQuality:quality,lastSeen:now()}}
function levelFromXp(xp){const base=160;let lvl=1,need=base;let x=xp;while(x>=need&&lvl<99){x-=need;lvl++;need=Math.floor(base*(1+(lvl-1)*.18))}return{lvl,x,need,pct:need?Math.round(x/need*100):0}}
function award(xp,coins=0){const before=levelFromXp(save.xp).lvl;save.xp+=xp;save.coins+=coins;const after=levelFromXp(save.xp).lvl;if(after>before){toast(`Рівень ${after} 🎉`);haptic('success')}persistLocal()}
function touchActivity(){const t=todayKey();if(save.lastActivity===t)return;if(save.lastActivity){const prev=new Date(save.lastActivity);prev.setDate(prev.getDate()+1);const target=prev.toISOString().slice(0,10);save.streak=target===t?save.streak+1:1}else save.streak=1;save.lastActivity=t}
function speakText(text,rate=save.settings.voiceRate){if(!text||!('speechSynthesis' in window))return false;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=clamp(rate,.65,1.15);u.pitch=1;const wanted=save.settings.voiceName;if(wanted!=='auto'){const v=voiceList.find(x=>x.name===wanted);if(v)u.voice=v}else{const v=voiceList.find(x=>/^de(-|_)?/i.test(x.lang))||voiceList.find(x=>/german|deutsch/i.test(x.name));if(v)u.voice=v}u.volume=1;speechSynthesis.speak(u);return true}catch{return false}}
function speakGerman(text){if(!speakText(text)){toast('Озвучка недоступна у цьому браузері')}}
function sentenceUa(w){const map={'Das ist ein gutes Beispiel für unsere Arbeit.':'Це хороший приклад для нашої роботи.','Wir entwickeln eine neue Web-App.':'Ми розробляємо новий вебзастосунок.','Das ist eine tolle Gelegenheit.':'Це чудова можливість.','Er ist ein sehr zuverlässiger Partner.':'Він дуже надійний партнер.','Diese Prüfung ist eine große Herausforderung.':'Цей іспит — велике випробування.'};return map[w.sentence]||''}

function buildNav(){const html=navItems.map(([id,icon,label])=>`<button data-nav="${id}"><span class="ico">${icon}</span><span>${label}</span></button>`).join('');$('sideNav').innerHTML=html;$('bottomNav').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)))}
function nav(screen){if(!titles[screen])return;state.screen=screen;$('pageTitle').textContent=titles[screen][0];$('pageSubtitle').textContent=titles[screen][1];document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===`screen-${screen}`));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===screen));if(screen==='anki')prepareAnkiSession();renderAll();syncTelegramBackButton();if(tg?.MainButton){try{tg.MainButton.hide()}catch{}}if(screen==='anki'&&state.ankiRevealed)syncTelegramMainButton()}

function renderHeader(){const l=levelFromXp(save.xp);$('level').textContent=l.lvl;$('resources').innerHTML=`<div class="res">XP <b>${save.xp}</b></div><div class="res">Серія <b>🔥 ${save.streak}</b></div>`;const learned=Math.min(save.learnedToday,save.dailyGoal);const pct=Math.round(learned/save.dailyGoal*100);$('sideProgress').style.width=`${pct}%`;$('sideLearned').textContent=learned;$('sideGoal').textContent=save.dailyGoal}
function renderDashboard(){const r=recommendedWord();const list=dueWords();$('homeWord').textContent=r?.german||'—';$('homeGrammar').textContent=r?.grammar||'';$('homeMeaning').textContent=r?.ukrainian||'—';$('homeExample').textContent=r?.sentence||'Додай перші слова, щоб почати.';$('todayLabel').textContent=todayKey();$('dDue').textContent=list.length;$('dMastered').textContent=mergedWords().filter(w=>mastery(w)>=5).length;$('dAccuracy').textContent=save.answers?`${Math.round(save.correct/save.answers*100)}%`:'0%';$('homeStreak').textContent=save.streak;const pct=Math.round(Math.min(save.learnedToday,save.dailyGoal)/save.dailyGoal*100);$('dailyProgressBar').style.width=`${pct}%`;$('dailyCount').textContent=`${Math.min(save.learnedToday,save.dailyGoal)} / ${save.dailyGoal}`;$('dailyPercent').textContent=`${pct}%`}
function renderWords(){const all=mergedWords();const q=String($('search')?.value||'').toLowerCase().trim();const filtered=all.filter(w=>!q||`${w.german} ${w.ukrainian}`.toLowerCase().includes(q));$('wordCountText').textContent=`${all.length} слів`;$('wTotal').textContent=all.length;$('wNew').textContent=all.filter(w=>mastery(w)===0).length;$('wLearning').textContent=all.filter(w=>mastery(w)>0&&mastery(w)<5).length;$('wMastered').textContent=all.filter(w=>mastery(w)>=5).length;$('wordList').innerHTML=filtered.map(w=>{const m=mastery(w);const r=save.review[wordKey(w)]||{};const due=(Number(r.dueAt)||0)<=now();return `<div class="word-item"><div><div class="de">${esc(w.german)}</div><div class="ua">${esc(w.ukrainian)}</div></div><div class="meta"><span class="badge">${esc(w.level||'A2/B1')}</span><span class="badge">${m}/5</span><span class="badge">${due?'До повторення':'Заплановано'}</span><button class="icon-btn mini-speak" data-word="${esc(w.german)}" title="Озвучити">🔊</button></div></div>`}).join('')||'<div class="muted small">Нічого не знайдено.</div>';document.querySelectorAll('.mini-speak').forEach(b=>b.addEventListener('click',()=>speakGerman(b.dataset.word)))}
function prepareAnkiSession(){const pool=dueWords();const all=mergedWords();state.sessionCards=pool.length?pool.slice(0,Math.min(20,pool.length)):[...all].sort((a,b)=>mastery(a)-mastery(b)).slice(0,Math.min(20,all.length));if(!state.sessionCards.length)state.sessionCards=[{german:'—',ukrainian:'Додай слово',grammar:'',sentence:'',level:'A2/B1'}];state.ankiIndex=0;state.ankiRevealed=false;state.sessionAnswerLock=false;renderAnki()}
function currentCard(){return state.sessionCards[state.ankiIndex]||state.sessionCards[0]}
function renderAnki(){const w=currentCard();const r=save.review[wordKey(w)]||{};const m=mastery(w);$('ankiPosition').textContent=`${Math.min(state.ankiIndex+1,state.sessionCards.length)} / ${state.sessionCards.length}`;$('ankiStage').textContent=m===0?'NEW':`MASTERY ${m}/5`;$('ankiLevel').textContent=w.level||'A2/B1';$('ankiWord').textContent=w.german||'—';$('ankiGrammar').textContent=w.grammar||'';$('ankiMeaning').textContent=w.ukrainian||'—';$('ankiSentence').textContent=w.sentence||'—';$('ankiSentenceUa').textContent=sentenceUa(w);$('ankiCard').classList.toggle('revealed',state.ankiRevealed);$('showAnswer').classList.toggle('hide',state.ankiRevealed);$('rateWrap').classList.toggle('hide',!state.ankiRevealed);const box=Number(r.box)||0;$('ankiNext').textContent=state.ankiRevealed?`Поточний рівень памʼяті: ${box}/5`:'Спробуй згадати переклад до відкриття.';$('aToday').textContent=save.learnedToday;$('aDue').textContent=dueWords().length;$('aAccuracy').textContent=save.answers?`${Math.round(save.correct/save.answers*100)}%`:'0%';$('aStreak').textContent=save.streak}
function rateCard(quality){if(state.sessionAnswerLock||!state.ankiRevealed)return;state.sessionAnswerLock=true;const w=currentCard();const before=mastery(w);const k=wordKey(w);save.answers++;if(quality>=4){save.correct++;save.mastery[k]=clamp(before+1,0,5);setReview(w,quality);award(8,0)}else if(quality===2){save.correct++;save.mastery[k]=clamp(before,0,5);setReview(w,quality);award(5,0)}else{save.errors++;save.mastery[k]=Math.max(0,before-1);setReview(w,quality);award(3,0)}save.learnedToday++;touchActivity();persistLocal();haptic(quality>=4?'success':'light');const done=state.ankiIndex>=state.sessionCards.length-1;toast(quality>=4?'Добре! Слово закріплено.':quality===2?'Добре, ще раз повторимо пізніше.':'Нічого страшного — це слово повернеться швидше.');if(done){setTimeout(()=>{state.sessionAnswerLock=false;prepareAnkiSession();},450)}else{setTimeout(()=>{state.sessionAnswerLock=false;state.ankiIndex++;state.ankiRevealed=false;renderAll();syncTelegramMainButton();if(save.settings.autoSpeak)speakGerman(currentCard().german)},450)}}
function addWord(){const de=$('addDe').value.trim();const ua=$('addUa').value.trim();const ex=$('addEx').value.trim();if(!de||!ua){toast('Вкажи слово та переклад');return}if(mergedWords().some(w=>w.german.toLowerCase()===de.toLowerCase())){toast('Це слово вже є у колекції');return}save.customWords.unshift({id:uid(),german:de,ukrainian:ua,grammar:'',sentence:ex,level:'A2/B1',category:'Мої слова',rarity:'звичайний'});persistLocal();$('addDe').value='';$('addUa').value='';$('addEx').value='';$('addBox').classList.add('hide');renderAll();toast('Слово додано ✅')}
function toggleAnswer(){state.ankiRevealed=true;renderAnki();haptic('light');if(save.settings.autoSpeak)speakGerman(currentCard().german);syncTelegramMainButton()}
function renderProfile(){const l=levelFromXp(save.xp);$('pLevel').textContent=l.lvl;$('pXp').textContent=save.xp;$('pWords').textContent=mergedWords().length;$('pMastered').textContent=mergedWords().filter(w=>mastery(w)>=5).length;$('pStreak').textContent=save.streak;$('pAccuracy').textContent=save.answers?`${Math.round(save.correct/save.answers*100)}%`:'0%';$('themeSwitch').classList.toggle('on',save.settings.theme==='dark');$('motionSwitch').classList.toggle('on',save.settings.reducedMotion);$('voiceRate').value=String(save.settings.voiceRate);$('autoSpeak').checked=save.settings.autoSpeak;setSyncStatus(telegramReady?'Telegram Mini App · синхронізація':'Браузерний режим · localStorage')}
function renderAll(){renderHeader();renderDashboard();renderWords();renderAnki();renderProfile()}
function showToast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
const toast=showToast;
function haptic(type){try{if(tg?.HapticFeedback){if(type==='success')tg.HapticFeedback.notificationOccurred('success');else if(type==='error')tg.HapticFeedback.notificationOccurred('error');else tg.HapticFeedback.impactOccurred(type==='heavy'?'heavy':'light')}}catch{}}

function applyTelegramTheme(){const p=tg?.themeParams||{};const root=document.documentElement;const map={bg_color:'--tg-bg',secondary_bg_color:'--tg-secondary',text_color:'--tg-text',hint_color:'--tg-hint',button_color:'--tg-button',button_text_color:'--tg-button-text'};Object.entries(map).forEach(([k,v])=>{if(p[k])root.style.setProperty(v,p[k])});if(p.bg_color)root.style.setProperty('--bg',p.bg_color);if(p.secondary_bg_color)root.style.setProperty('--panel',p.secondary_bg_color);if(p.text_color)root.style.setProperty('--text',p.text_color);if(p.hint_color)root.style.setProperty('--muted',p.hint_color)}
function applySafeArea(){const root=document.documentElement;const s=tg?.safeAreaInset||{};const c=tg?.contentSafeAreaInset||{};root.style.setProperty('--tg-safe-top',`${Number(s.top||0)}px`);root.style.setProperty('--tg-safe-right',`${Number(s.right||0)}px`);root.style.setProperty('--tg-safe-bottom',`${Number(s.bottom||0)}px`);root.style.setProperty('--tg-safe-left',`${Number(s.left||0)}px`);root.style.setProperty('--tg-content-top',`${Number(c.top||0)}px`);root.style.setProperty('--tg-content-bottom',`${Number(c.bottom||0)}px`);if(tg?.viewportHeight)root.style.setProperty('--tg-vh',`${tg.viewportHeight}px`)}
function syncTelegramBackButton(){if(!tg?.BackButton)return;try{state.screen==='dashboard'?tg.BackButton.hide():tg.BackButton.show()}catch{}}
function syncTelegramMainButton(){if(!tg?.MainButton)return;try{if(state.screen==='anki'&&!state.ankiRevealed){tg.MainButton.setText('ПОКАЗАТИ ПЕРЕКЛАД');tg.MainButton.show()}else if(state.screen==='anki'&&state.ankiRevealed){tg.MainButton.hide()}else{tg.MainButton.hide()}}catch{}}
function setSyncStatus(text){const el=$('tgSyncStatus');if(el)el.textContent=text}
function loadTelegramSdk(timeout=1400){if(window.Telegram?.WebApp)return Promise.resolve(true);return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const s=document.createElement('script');s.src='https://telegram.org/js/telegram-web-app.js';s.async=true;s.onload=()=>finish(Boolean(window.Telegram?.WebApp));s.onerror=()=>finish(false);document.head.appendChild(s);setTimeout(()=>finish(Boolean(window.Telegram?.WebApp)),timeout)})}
function getTg(){try{return window.Telegram?.WebApp||null}catch{return null}}
function telegramConfirm(message){return new Promise(resolve=>{if(tg?.showConfirm){try{return tg.showConfirm(message,ok=>resolve(Boolean(ok)))}catch{}}resolve(window.confirm(message))})}
function chunkObject(str,size=3000){const out=[];for(let i=0;i<str.length;i+=size)out.push(str.slice(i,i+size));return out}
async function cloudSave(){if(!tg?.CloudStorage)return false;try{const json=JSON.stringify(save);const chunks=chunkObject(json,2800);const payload={};chunks.forEach((c,i)=>payload[`${TG_CHUNK_PREFIX}${i}`]=c);payload[`${TG_CHUNK_PREFIX}count`]=String(chunks.length);await new Promise((res,rej)=>tg.CloudStorage.setItem(Object.keys(payload)[0],payload[Object.keys(payload)[0]],e=>e?rej(e):res()));for(const k of Object.keys(payload).slice(1)){await new Promise((res,rej)=>tg.CloudStorage.setItem(k,payload[k],e=>e?rej(e):res()))}return true}catch{return false}}
async function cloudLoad(){if(!tg?.CloudStorage)return null;try{const count=await new Promise((res,rej)=>tg.CloudStorage.getItem(`${TG_CHUNK_PREFIX}count`,(e,v)=>e?rej(e):res(Number(v)||0)));if(!count)return null;const keys=Array.from({length:count},(_,i)=>`${TG_CHUNK_PREFIX}${i}`);const vals=await new Promise((res,rej)=>tg.CloudStorage.getItems(keys,(e,v)=>e?rej(e):res(v||{})));let json='';for(const k of keys)json+=vals[k]||'';return json?normalizeSave(JSON.parse(json)):null}catch{return null}}
async function hydrateTelegram(){if(!tg?.CloudStorage)return;const remote=await cloudLoad();if(remote){const localScore=save.xp+save.learnedToday*3+save.correct;const remoteScore=remote.xp+remote.learnedToday*3+remote.correct;save=remoteScore>localScore?remote:save;persistLocal()}setSyncStatus('Telegram Mini App · готово')}
async function syncNow(){if(!tg){toast('Синхронізація доступна у Telegram');return}persistLocal();setSyncStatus('Синхронізація…');const ok=await cloudSave();setSyncStatus(ok?'Синхронізовано ✅':'Синхронізація недоступна');toast(ok?'Прогрес збережено в Telegram ✅':'Не вдалося синхронізувати')}

function setupVoices(){if(!('speechSynthesis' in window))return;const refresh=()=>{voiceList=speechSynthesis.getVoices().filter(v=>/de(-|_)/i.test(v.lang)||/german|deutsch/i.test(v.name));const select=$('voiceSelect');if(!select)return;const current=save.settings.voiceName;select.innerHTML='<option value="auto">Автоматично</option>'+voiceList.map(v=>`<option value="${esc(v.name)}">${esc(v.name)} · ${esc(v.lang)}</option>`).join('');select.value=voiceList.some(v=>v.name===current)?current:'auto'};refresh();speechSynthesis.onvoiceschanged=refresh}

function exportProgress(){const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`gestalt-progress-v${VERSION}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Прогрес експортовано')}
function importProgress(file){const rd=new FileReader();rd.onload=()=>{try{save=normalizeSave(JSON.parse(rd.result));persistLocal();renderAll();nav('dashboard');toast('Прогрес імпортовано ✅')}catch{toast('Помилка імпорту')}};rd.readAsText(file)}
function bind(){
  $('showAdd').addEventListener('click',()=>$('addBox').classList.toggle('hide'));$('addBtn').addEventListener('click',addWord);$('search').addEventListener('input',renderWords);$('homeSpeak').addEventListener('click',()=>{const w=recommendedWord();if(w)speakGerman(w.german)});
  $('showAnswer').addEventListener('click',toggleAnswer);$('speakWord').addEventListener('click',()=>speakGerman(currentCard().german));$('speakSentence').addEventListener('click',()=>speakGerman(currentCard().sentence));document.querySelectorAll('[data-rate]').forEach(b=>b.addEventListener('click',()=>rateCard(Number(b.dataset.rate))));
  $('themeSwitch').addEventListener('click',()=>{save.settings.theme=save.settings.theme==='dark'?'light':'dark';syncTheme();persistLocal();renderProfile()});$('motionSwitch').addEventListener('click',()=>{save.settings.reducedMotion=!save.settings.reducedMotion;syncTheme();persistLocal();renderProfile()});
  $('voiceRate').addEventListener('change',e=>{save.settings.voiceRate=clamp(Number(e.target.value)||.9,.65,1.15);persistLocal()});$('voiceSelect').addEventListener('change',e=>{save.settings.voiceName=e.target.value;persistLocal()});$('autoSpeak').addEventListener('change',e=>{save.settings.autoSpeak=e.target.checked;persistLocal()});
  $('tgSyncBtn')?.addEventListener('click',syncNow);$('exportBtn').addEventListener('click',exportProgress);$('importFile').addEventListener('change',e=>{if(e.target.files?.[0])importProgress(e.target.files[0]);e.target.value=''});$('resetAll').addEventListener('click',async()=>{if(!await telegramConfirm('Видалити локальний прогрес?'))return;safeRemove(SAVE_KEY);location.reload()});
}
function syncTheme(){document.documentElement.style.colorScheme=save.settings.theme;document.documentElement.dataset.theme=save.settings.theme;document.documentElement.classList.toggle('reduced-motion',save.settings.reducedMotion)}
async function initTelegram(){await loadTelegramSdk();tg=getTg();if(!tg)return;try{telegramReady=true;tg.ready();tg.expand();if(tg.disableVerticalSwipes)tg.disableVerticalSwipes();applyTelegramTheme();applySafeArea();tg.onEvent?.('themeChanged',()=>{applyTelegramTheme();applySafeArea()});tg.onEvent?.('viewportChanged',applySafeArea);tg.onEvent?.('safeAreaChanged',applySafeArea);tg.onEvent?.('contentSafeAreaChanged',applySafeArea);tg.BackButton?.onClick(()=>nav('dashboard'));tg.MainButton?.onClick(()=>{if(state.screen==='anki'&&!state.ankiRevealed)toggleAnswer()});setSyncStatus('Telegram Mini App · підключено')}catch{telegramReady=false}}

async function boot(){
  loadLocal();
  await initTelegram();
  try{const r=await fetch(WORDS_URL,{cache:'default'});if(!r.ok)throw new Error('words');const data=await r.json();if(!Array.isArray(data))throw new Error('format');words=data}catch{words=[];toast('Не вдалося завантажити словник. Спробуй оновити сторінку.')} 
  await hydrateTelegram();
  buildNav();bind();setupVoices();syncTheme();renderAll();nav('dashboard');
  if('serviceWorker' in navigator){try{await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready}catch{}}
}
boot().catch(()=>toast('GESTALT не зміг запустити модулі. Онови сторінку.'));
