
const VERSION='0.008';
const WORDS_URL='./data/words.json';
const SAVE_KEY='gestalt_v008_save';
const INTERVALS=[1,2,4,7,14,30];
const navItems=[['dashboard','⌂','Головна'],['words','▣','Слова'],['anki','▤','Anki'],['dice','◉','Dice'],['profile','⚙','Профіль']];
const titles={dashboard:['Головне меню','Центр керування: вчи, повторюй, грай та прокачуйся'],words:['Вивчення слів','Додавай слова та вчи їх'],anki:['Картки Anki','Інтелектуальна система повторення SRS'],dice:['Random Dice','Кинь кубик і отримай випадкову карту'],profile:['Профіль та налаштування','Твій прогрес, резервні копії та налаштування']};
let words=[];let save={};let state={screen:'dashboard',ankiIndex:0,ankiRevealed:false};
const $=id=>document.getElementById(id);
function uid(){return 'u-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function today(){const d=new Date();d.setHours(0,0,0,0);return d}
function dateKey(d=new Date()){return new Intl.DateTimeFormat('en-CA').format(d)}
function safeStorage(){try{const k='__g';localStorage.setItem(k,'1');localStorage.removeItem(k);return true}catch{return false}}
function load(){
  const defaults={xp:0,level:1,streak:0,lastOpen:null,gold:0,gems:0,energy:5,mastery:{},reviews:{},errors:0,answers:0,correct:0,customWords:[],bestWave:0,dice:{wave:1,base:100,mana:30,power:0,combo:0,board:Array(15).fill(null),enemies:[],running:false},settings:{theme:'dark',reducedMotion:false}};
  try{save=JSON.parse(localStorage.getItem(SAVE_KEY)||'null')||defaults}catch{save=defaults}
  save={...defaults,...save,mastery:save.mastery||{},reviews:save.reviews||{},customWords:Array.isArray(save.customWords)?save.customWords:[],dice:{...defaults.dice,...(save.dice||{}),board:Array.isArray(save.dice?.board)?save.dice.board:Array(15).fill(null),enemies:Array.isArray(save.dice?.enemies)?save.dice.enemies:[]},settings:{...defaults.settings,...(save.settings||{})}};
  // migrate common old progress keys without overwriting new save
  if(!localStorage.getItem(SAVE_KEY)){
    try{const p=JSON.parse(localStorage.getItem('de_b1_rpg_progress_v3')||'null');if(p){save.xp=Number(p.xp||0);save.level=Number(p.level||1);save.streak=Number(p.streak||0);save.gold=Number(p.gold||0);}}
    catch{}
    try{const m=JSON.parse(localStorage.getItem('deutsch_quest_v002')||'null');if(m?.mastery)save.mastery={...m.mastery};}catch{}
  }
  persist();
}
function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch{}}
function mergedWords(){return [...words,...save.customWords]}
function mastery(w){return Number(save.mastery[w.id||w.german]||0)}
function due(w){const r=save.reviews[w.id||w.german];return !r || !r.next || new Date(r.next)<=today()}
function setReview(w,r){save.reviews[w.id||w.german]=r}
function levelFromXp(xp){let lvl=1,need=100;let x=xp;while(x>=need){x-=need;lvl++;need=100+lvl*25}return {lvl,xpInLevel:x,need}}
function award(xp,coins=0){save.xp+=xp;save.gold+=coins;const l=levelFromXp(save.xp);if(l.lvl!==save.level){save.level=l.lvl;toast(`Новий рівень: ${l.lvl} 🎉`)}persist();renderAll()}
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function nav(screen){state.screen=screen;document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$('screen-'+screen)?.classList.add('active');document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===screen));$('pageTitle').textContent=titles[screen][0];$('pageSubtitle').textContent=titles[screen][1];if(screen==='anki')renderAnki();if(screen==='dice')renderDice();renderAll()}
function buildNav(){const side=$('sideNav'),bottom=$('bottomNav');side.innerHTML=navItems.map(([id,ico,label])=>`<button data-nav="${id}"><span class="ico">${ico}</span>${label}</button>`).join('');bottom.innerHTML=navItems.map(([id,ico,label])=>`<button data-nav="${id}"><div style="font-size:18px">${ico}</div>${label}</button>`).join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)nav(b.dataset.nav)})}
function renderHeader(){const l=levelFromXp(save.xp);$('level').textContent=l.lvl;$('resources').innerHTML=`<div class="res">🪙 <b>${save.gold}</b></div><div class="res">◈ <b>${save.gems}</b></div><div class="res">⚡ <b>${save.energy}</b></div>`;$('heroName').textContent='Wanderer';$('homeLevel').textContent=l.lvl;$('homeXp').textContent=save.xp;$('homeStreak').textContent=save.streak;const d=new Date();$('todayLabel').textContent=d.toLocaleDateString('uk-UA',{day:'2-digit',month:'2-digit',year:'numeric'})}
function renderDashboard(){const all=mergedWords();const mastered=all.filter(w=>mastery(w)>=5).length;const learning=all.filter(w=>mastery(w)>0&&mastery(w)<5).length;const du=all.filter(due).length;const acc=save.answers?Math.round(save.correct/save.answers*100):0;$('dTotal').textContent=all.length;$('dMastered').textContent=mastered;$('dDue').textContent=du;$('dAccuracy').textContent=acc+'%';const rec=all.filter(due).sort((a,b)=>mastery(a)-mastery(b))[0]||all[0];if(rec){$('recommendation').textContent=rec.german;$('recommendationMeaning').textContent=rec.ukrainian}}
function renderWords(){const all=mergedWords();$('wTotal').textContent=all.length;$('wMastered').textContent=all.filter(w=>mastery(w)>=5).length;$('wLearning').textContent=all.filter(w=>mastery(w)>0&&mastery(w)<5).length;$('wNew').textContent=all.filter(w=>mastery(w)===0).length;$('wordCountText').textContent=all.length+' слів';const q=($('search').value||'').trim().toLowerCase();const list=all.filter(w=>(w.german+' '+w.ukrainian+' '+(w.sentence||'')).toLowerCase().includes(q)).slice(0,200);$('wordList').innerHTML=list.map(w=>{const m=mastery(w),r=save.reviews[w.id||w.german];return `<div class="word-item"><div><div class="de">${esc(w.german)}</div><div class="ua">${esc(w.ukrainian)}${w.sentence?' · '+esc(w.sentence):''}</div></div><div style="display:flex;gap:6px;align-items:center"><span class="badge">${m}/5</span><span class="badge">${r&&r.next?new Date(r.next).toLocaleDateString('uk-UA',{day:'2-digit',month:'2-digit'}):'нове'}</span></div></div>`}).join('')||'<div class="muted">Нічого не знайдено.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dueWords(){return mergedWords().filter(due)}
function renderAnki(){const list=dueWords().length?dueWords():mergedWords();if(!list.length)return;state.ankiIndex=Math.max(0,Math.min(state.ankiIndex,list.length-1));const w=list[state.ankiIndex];$('ankiPosition').textContent=`${state.ankiIndex+1} / ${list.length}`;$('ankiWord').textContent=w.german;$('ankiGrammar').textContent=w.grammar||'';$('ankiMeaning').textContent=state.ankiRevealed?w.ukrainian:'Натисни «Показати відповідь»';$('ankiSentence').innerHTML=state.ankiRevealed?(esc(w.sentence||'')):'—';$('rateWrap').classList.toggle('hide',!state.ankiRevealed);$('showAnswer').classList.toggle('hide',state.ankiRevealed);$('aDue').textContent=dueWords().length;$('aLearned').textContent=mergedWords().filter(w=>mastery(w)>=5).length;$('aStreak').textContent=save.streak;$('aErrors').textContent=save.errors;$('ankiNext').textContent=state.ankiRevealed?'Оціни картку, щоб продовжити.':'Почни з показу відповіді.'}
function rateCard(q){const list=dueWords().length?dueWords():mergedWords();if(!list.length)return;const w=list[state.ankiIndex];const key=w.id||w.german;let m=mastery(w);save.answers++;if(q>=3){m=Math.min(5,m+1);save.correct++;save.streak=Math.max(1,save.streak+1);award(12,4)}else{m=Math.max(0,m-1);save.errors++;save.streak=0;award(4,1)}const days=INTERVALS[Math.min(m,INTERVALS.length-1)];const next=new Date();next.setDate(next.getDate()+days);setReview(w,{next:next.toISOString(),q,m});save.mastery[key]=m;persist();state.ankiRevealed=false;state.ankiIndex=(state.ankiIndex+1)%Math.max(1,list.length);toast(q>=3?`Добре! Mastery ${m}/5`:`Повернули в цикл повторення`);renderAll()}
const diceTypes=[{id:'scribe',icon:'✒️',base:10,cls:'common'},{id:'sage',icon:'📚',base:13,cls:'rare'},{id:'seer',icon:'🔮',base:17,cls:'epic'},{id:'rune',icon:'✦',base:22,cls:'legend'}];
function newBattle(){save.dice={wave:1,base:100,mana:30,power:0,combo:0,board:Array(15).fill(null),enemies:[],running:false};persist()}
function randomWord(){const all=mergedWords();return all[Math.floor(Math.random()*all.length)]}
function spawnDie(){if(save.dice.mana<5){toast('Недостатньо мани');return}const i=save.dice.board.findIndex(x=>!x);if(i<0){toast('Поле заповнене — зроби merge');return}save.dice.mana-=5;const t=diceTypes[Math.floor(Math.random()*diceTypes.length)];save.dice.board[i]={type:t.id,level:1,word:randomWord()};save.dice.power+=t.base;persist();renderDice()}
function dieDamage(d){const t=diceTypes.find(x=>x.id===d.type)||diceTypes[0];return Math.round(t.base*d.level*(1+(d.level-1)*.18))}
function renderBoard(){const b=$('board');b.innerHTML=save.dice.board.map((d,i)=>{if(!d)return `<button class="cell" data-cell="${i}">＋</button>`;const t=diceTypes.find(x=>x.id===d.type)||diceTypes[0];return `<button class="cell" data-cell="${i}"><div class="die ${t.cls}"><b>${t.icon}</b><span>${esc(d.word.german)}</span><span class="lvl">Lv.${d.level}</span></div></button>`}).join('')}
function mergeAt(a,b){if(!save.dice.board[a]||!save.dice.board[b])return false;if(save.dice.board[a].type!==save.dice.board[b].type||save.dice.board[a].level!==save.dice.board[b].level)return false;const die=save.dice.board[a];die.level++;die.word=randomWord();save.dice.board[a]=die;save.dice.board[b]=null;save.dice.combo=Math.min(9,save.dice.combo+1);save.dice.power+=dieDamage(die);persist();toast(`MERGE → Lv.${die.level}`);return true}
function autoMerge(){for(let level=1;level<6;level++){for(const t of diceTypes){let idx=save.dice.board.map((d,i)=>d&&d.type===t.id&&d.level===level?i:-1).filter(i=>i>=0);while(idx.length>=2){mergeAt(idx[0],idx[1]);idx=save.dice.board.map((d,i)=>d&&d.type===t.id&&d.level===level?i:-1).filter(i=>i>=0)}}}renderDice()}
let selected=-1;
function selectCell(i){if(!save.dice.board[i]){spawnDie();return}if(selected<0){selected=i;renderDice();return}if(selected===i){selected=-1;renderDice();return}if(!mergeAt(selected,i)){toast('Можна обʼєднати лише однакові кубики');selected=-1;renderDice()}else{selected=-1;renderDice()}}
function startWave(){if(save.dice.running){toast('Хвиля вже триває');return}if(save.dice.base<=0){newBattle();renderDice();toast('Бій скинуто — починаємо новий run');return}save.dice.running=true;save.dice.enemies=Array.from({length:Math.min(5,Math.max(2,save.dice.wave+1))},(_,i)=>({id:uid(),hp:35+save.dice.wave*18+i*8,max:35+save.dice.wave*18+i*8,boss:save.dice.wave%5===0&&i===0,emoji:i===0?'👹':'👾'}));persist();renderDice();askBattleQuestion()}
function askBattleQuestion(){const w=randomWord();const all=mergedWords();const wrong=all.filter(x=>x.id!==w.id).sort(()=>Math.random()-.5).slice(0,3);const opts=[w,...wrong].sort(()=>Math.random()-.5);$('qWord').textContent=w.german;$('qPrompt').textContent='Обери правильний переклад';$('answers').innerHTML=opts.map(x=>`<button class="answer" data-answer="${esc(x.id||x.german)}">${esc(x.ukrainian)}</button>`).join('');$('answers').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>answerBattle(w,btn.dataset.answer))) }
function answerBattle(w,id){const ok=id===(w.id||w.german);save.answers++;if(ok){save.correct++;save.dice.combo=Math.min(9,save.dice.combo+1);save.dice.power+=12;award(10,3);$('qResult').textContent='✓ Правильно — Language Power +12';$('qResult').style.color='#78dd9c'}else{save.errors++;save.dice.combo=0;$('qResult').textContent=`✕ Правильна відповідь: ${w.ukrainian}`;$('qResult').style.color='#ef8a84'}const damage=Math.max(8,Math.floor(save.dice.power*(ok?1+.08*save.dice.combo:0.35)));let remaining=damage;for(const e of save.dice.enemies){if(remaining<=0)break;const dealt=Math.min(e.hp,remaining);e.hp-=dealt;remaining-=dealt}save.dice.enemies=save.dice.enemies.filter(e=>e.hp>0);if(!save.dice.enemies.length){finishWave();return}save.dice.base=Math.max(0,save.dice.base-(ok?0:8));save.dice.mana=Math.min(40,save.dice.mana+5);persist();renderDice();if(save.dice.base<=0){save.dice.running=false;toast('База знищена');renderDice()}} 
function finishWave(){const wasBoss=save.dice.wave%5===0;award(25+(wasBoss?50:0),10+(wasBoss?20:0));save.dice.running=false;save.dice.wave++;if(save.dice.wave>10){save.bestWave=Math.max(save.bestWave,10);toast('Перемога! 10 хвиль завершено 🏆');newBattle();return}save.bestWave=Math.max(save.bestWave,save.dice.wave-1);save.dice.mana=Math.min(40,save.dice.mana+10);save.dice.power=Math.max(0,Math.floor(save.dice.power*.92));persist();toast(wasBoss?'Boss переможено!':'Хвилю переможено!');renderDice()}
function renderDice(){renderBoard();$('wave').textContent=`${save.dice.wave}/10`;$('base').textContent=save.dice.base;$('mana').textContent=save.dice.mana;$('power').textContent=save.dice.power;$('combo').textContent='x'+save.dice.combo;$('enemies').innerHTML=save.dice.enemies.length?save.dice.enemies.map(e=>`<div class="enemy"><div style="font-size:22px">${e.emoji}</div><small>${e.boss?'BOSS':'Ворог'}</small><div class="hp"><i style="width:${Math.max(0,e.hp/e.max*100)}%"></i></div></div>`).join(''):'<div class="muted">Запусти хвилю</div>';if(!save.dice.running){$('qWord').textContent=save.dice.wave>10?'Вітаємо!':'Запусти хвилю';$('qPrompt').textContent='Правильна відповідь посилює атаку';$('answers').innerHTML=''}$('qTimer').textContent=save.dice.running?'LIVE':'READY'}
function renderProfile(){const l=levelFromXp(save.xp);$('pLevel').textContent=l.lvl;$('pXp').textContent=save.xp;$('pWords').textContent=mergedWords().length;$('pMastered').textContent=mergedWords().filter(w=>mastery(w)>=5).length;$('pStreak').textContent=save.streak;$('pBestWave').textContent=save.bestWave;$('themeSwitch').classList.toggle('on',save.settings.theme==='dark');$('motionSwitch').classList.toggle('on',!!save.settings.reducedMotion);document.documentElement.dataset.motion=save.settings.reducedMotion?'reduced':'normal'}
function renderAll(){renderHeader();renderDashboard();renderWords();renderAnki();renderProfile()}
function initTelegram(){const tg=window.Telegram?.WebApp;if(!tg)return;try{tg.ready();tg.expand();tg.setHeaderColor('#061015');tg.setBackgroundColor('#030708');if(tg.enableClosingConfirmation)tg.enableClosingConfirmation(false);if(tg.onEvent)tg.onEvent('themeChanged',()=>{const t=window.Telegram?.WebApp?.themeParams||{};if(t.bg_color)document.documentElement.style.setProperty('--bg',t.bg_color);if(t.secondary_bg_color)document.documentElement.style.setProperty('--panel',t.secondary_bg_color)});if(tg.BackButton){const sync=()=>{try{state.screen==='dashboard'?tg.BackButton.hide():tg.BackButton.show()}catch{}};tg.BackButton.onClick(()=>nav('dashboard'));sync();document.addEventListener('click',()=>setTimeout(sync,0),{passive:true})}}catch{}}
function syncTheme(){document.documentElement.style.colorScheme='dark';document.documentElement.classList.toggle('reduced-motion',!!save.settings.reducedMotion)}
async function boot(){
  load(); buildNav(); initTelegram();
  try{const r=await fetch(WORDS_URL,{cache:'no-store'});if(!r.ok)throw new Error('words');words=await r.json();if(!Array.isArray(words))throw new Error('format')}catch{words=[];toast('Не вдалося завантажити словник — працюємо в offline режимі')}
  document.querySelectorAll('[data-nav]').forEach(()=>{});
  $('showAdd').addEventListener('click',()=>$('addBox').classList.toggle('hide'));$('addBtn').addEventListener('click',addWord);$('search').addEventListener('input',renderWords);$('showAnswer').addEventListener('click',()=>{state.ankiRevealed=true;renderAnki()});document.querySelectorAll('[data-rate]').forEach(b=>b.addEventListener('click',()=>rateCard(Number(b.dataset.rate))));$('roll').addEventListener('click',spawnDie);$('startWave').addEventListener('click',startWave);$('autoMerge').addEventListener('click',autoMerge);$('resetDice').addEventListener('click',()=>{if(confirm('Скинути поточний бій?')){newBattle();renderDice()}});$('howDice').addEventListener('click',()=>toast('ROLL → MERGE → START WAVE → відповідай правильно → знищуй ворогів'));$('board').addEventListener('click',e=>{const c=e.target.closest('[data-cell]');if(c)selectCell(Number(c.dataset.cell))});$('themeSwitch').addEventListener('click',()=>{save.settings.theme=save.settings.theme==='dark'?'light':'dark';document.documentElement.style.colorScheme=save.settings.theme;document.body.style.background=save.settings.theme==='light'?'#eaf0f1':'';persist();renderProfile();toast(save.settings.theme==='dark'?'Темна тема':'Світла тема')});$('motionSwitch').addEventListener('click',()=>{save.settings.reducedMotion=!save.settings.reducedMotion;persist();syncTheme();renderProfile()});$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(save,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gestalt-progress-v0.008.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$('importFile').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{save={...save,...JSON.parse(rd.result)};persist();renderAll();toast('Прогрес імпортовано')}catch{toast('Помилка імпорту')}};rd.readAsText(f)});$('resetAll').addEventListener('click',()=>{if(confirm('Видалити локальний прогрес?')){localStorage.removeItem(SAVE_KEY);location.reload()}});syncTheme();nav('dashboard');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
boot();
