import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html'), css=read('css/main.css'), js=read('js/app.js'), sw=read('sw.js');
assert.match(html,/viewport-fit=cover/,'iOS safe-area viewport missing');
assert.match(css,/env\(safe-area-inset-bottom\)/,'safe-area bottom handling missing');
assert.match(css,/--tg-content-bottom/,'Telegram content inset variable missing');
assert.match(css,/@media\(max-width:640px\)/,'mobile breakpoint missing');
assert.match(css,/@media\(min-width:980px\)/,'desktop breakpoint missing');
assert.match(js,/AbortController/,'dictionary timeout missing');
assert.match(js,/COMPACT_WORDS_URL/,'compact dictionary path missing');
assert.match(js,/WORDS_URL/,'full dictionary fallback missing');
assert.match(sw,/networkFirst/,'dictionary network-first strategy missing');
assert.match(sw,/words\.compact\.json/,'compact dictionary missing from service worker');
assert.doesNotMatch(sw,/cache\.addAll\(ASSETS\)/,'service worker must not fail all install when one asset is slow');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'duplicate DOM ids');
console.log('PLATFORM STATIC CHECK OK');
