import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html');
const js=read('js/app.js');
const server=read('server/index.mjs');
const words=JSON.parse(read('data/words.json'));
const manifest=JSON.parse(read('data/book-vocabulary-manifest.json'));
const sw=read('sw.js');
assert.ok(Array.isArray(words)&&words.length>=900,'book vocabulary is incomplete');
assert.deepEqual(new Set(words.map(w=>w.topicNumber)),new Set([8,9,10,11,12,13,14]),'lessons 8-14 are not the whole bundled range');
assert.equal(words[0].topicNumber,8,'dataset must start at lesson 8');
assert.ok(words[0].german.includes('Witwer'),'lesson 8 order is not preserved');
assert.ok(words.some(w=>w.german==='schulpflichtig'),'end-of-book vocabulary missing');
assert.ok(words.every(w=>w.german&&w.ukrainian&&w.emoji&&w.sentence&&w.sentenceUa&&w.phonetic&&w.topicId&&w.sourcePage&&w.headword!==undefined&&w.pluralForm!==undefined),'word record missing required study/source fields');
assert.ok(words.every(w=>! /\(Sg\.?\)/i.test(w.headword)),'Sg marker leaked into headword');
assert.ok(words.every(w=>! /\(Sg\.?\)/i.test(w.phonetic)),'Sg marker leaked into phonetic');
assert.ok(words.every(w=>w.topicNumber>=8&&w.topicNumber<=14),'vocabulary outside lesson 8-14 present');
assert.equal(new Set(words.map(w=>w.id)).size,words.length,'duplicate word ids remain');
assert.ok(words.every(w=>String(w.german).trim()===String(w.headword).trim()),'display German field must match clean headword');
assert.ok(words.every(w=>!/[\(]Sg\.?[\)]|¨-|,\s*-|[\(]Pl\.?[\)]/i.test(String(w.german))), 'dictionary markers leaked into display German');
assert.equal(words.filter(w=>w.topicNumber===8 && w.emoji).length, manifest.byLesson['8'],'topic 8 emoji coverage incomplete');
assert.equal(words.filter(w=>w.topicNumber===14).length, manifest.byLesson['14'],'topic 14 count mismatch');
assert.doesNotMatch(html,/Random Dice|Battle Board|START WAVE|enemy|boss|spawnDie|autoMerge/i,'old game UI still present');
assert.doesNotMatch(js,/diceTypes|startWave|spawnDie|autoMerge|battleQuestion|Random Dice/i,'old game logic still present');
assert.ok(html.includes('id="flashcard"'),'flashcard missing');
assert.ok(html.includes('id="topicWordCount"'),'topic word count missing');
assert.ok(html.includes('id="rememberBtn"')&&html.includes('id="forgotBtn"'),'two-action controls missing');
assert.ok(html.includes('id="speakWord"')&&html.includes('id="speakSentence"'),'audio controls missing');
assert.ok(js.includes('speechSynthesis'),'speech synthesis missing');
assert.ok(js.includes('intervalForQuality')&&js.includes('mastery'),'SRS/mastery missing');
assert.ok(js.includes('const rawMastery=isObj(out.mastery)?out.mastery:{}'),'mastery migration boundary missing');
assert.ok(js.includes('save.mastery[k]=box'),'mastery must persist as the canonical 0–5 box value');
assert.ok(js.includes('Number(r.box||0)>=BALANCE.masteryBox'),'status must derive from canonical review state');

assert.match(js,/const BALANCE=\{dailyGoal:24,/,'balance source missing or self-referential');
assert.ok(js.includes('BALANCE.srsIntervals'),'SRS ladder not centralized');
assert.ok(js.includes('function updateCategoryCounts()'),'category counters function missing');
assert.ok(js.includes('countAll')&&js.includes('countNew')&&js.includes('countMastered'),'category counter rendering missing');
assert.ok(js.includes('const disabled=state.answerLock||!state.flipped'),'answer buttons must stay locked before reveal');
assert.ok(js.includes('state.flipped&&!state.answerLock'),'swipe answers must stay locked before reveal');
assert.ok(js.includes("if(mode==='review')"),'review mode must retain dedicated SRS selection');
assert.ok(!js.includes('const originalPickSession'),'pickSession must not be overridden after boot');
assert.ok(js.includes('phonetic(w.phonetic'),'phonetic rendering missing');
assert.ok(js.includes('COMPACT_WORDS_URL'),'compact dictionary loader missing');
assert.ok(sw.includes('gestalt-v0.031'),'service worker version mismatch');
assert.ok(sw.includes('words.compact.json'),'service worker compact dictionary missing');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const dup=ids.filter((id,i)=>ids.indexOf(id)!==i);assert.equal(new Set(dup).size,0,'duplicate ids: '+[...new Set(dup)].join(', '));
const refIds=[...js.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);
for(const id of new Set(refIds))assert.ok(ids.includes(id),'missing DOM id: '+id);
const css=read('css/main.css');
assert.match(css,/\.flashcard-inner\{[^}]*transform-style:preserve-3d/,'card inner must own the 3D context');
assert.match(css,/\.flashcard\.is-flipped \.flashcard-inner\{transform:rotateY\(180deg\)/,'flipped card must rotate only the inner layer');
assert.doesNotMatch(css,/\.flashcard\.is-flipped\{transform:/,'shell must not own the flip transform');
assert.doesNotMatch(css,/\.flashcard\.is-flipped \.flash-front\{transform:/,'flipped front must not add a second rotation');
assert.doesNotMatch(css,/\.flashcard\.is-flipped \.flash-back\{transform:/,'flipped back must not reset its 180deg local orientation');
assert.match(css,/\.flash-back\{[^}]*transform:rotateY\(180deg\)/,'back face must keep its 180deg local orientation');
assert.doesNotMatch(css,/\.flash-back\{[^}]*transform:none/,'back face must not be neutralized by a second transform');
assert.ok(html.includes('id="flashcardInner"'),'flashcard inner layer missing');
assert.ok(js.includes("$('backMeaning').textContent=w.ukrainian"),'back translation binding missing');
assert.ok(js.includes("$('sentencePanel').hidden=!state.sentenceExpanded"),'example must be collapsed by default');
assert.ok(js.includes("function updateCategoryCounts()"),'category count renderer missing');
assert.ok(js.includes('renderProgress();renderCard();renderStats();'),'daily progress must be refreshed with the main UI');
assert.ok(js.includes('statNew')&&js.includes('statReview')&&js.includes('statRepetitions')&&js.includes('statMasteryPct'),'statistics counters must be wired to runtime state');
assert.match(html,/id="flashcard"[^>]*role="button"/,'flashcard should expose keyboard/button semantics');
assert.ok(js.includes("const all=filterTopic(mergedWords(),state.currentTopic)"),'category counts must follow selected topic');
assert.match(css,/\.flash-face\{[^}]*backface-visibility:hidden/,'backface visibility missing');
assert.ok(!/\.flash-face\{[^}]*transform-style:flat/.test(css),'card faces should preserve the 3D track rather than force a flat compositing context');
assert.match(css,/\.flash-face\{[^}]*overflow:hidden/,'card faces must clip their own content cleanly');
assert.ok(css.includes('.flashcard.is-flipped .flashcard-inner{transform:rotateY(180deg)}'),'inner must own flip transform');
assert.match(css,/\.flash-back\{transform:rotateY\(180deg\)/,'back content must live on the canonical 3D back face');
assert.ok(html.includes('class="flash-face flash-back"'),'canonical back face missing');
assert.ok(js.includes("const VERSION='0.031'"),'app version must match release identity');
assert.ok(js.includes("wordEl.classList.remove('word-long','word-xlong')"),'long-word card sizing logic missing');
assert.equal(read('VERSION').trim(),'0.031','version file mismatch');
assert.equal(JSON.parse(read('package.json')).version,'0.0.31','package version mismatch');
assert.match(read('server/index.mjs'),/VERSION='0.031'/,'server version mismatch');
assert.match(read('sw.js'),/gestalt-v0\.031/,'service worker cache version mismatch');

assert.match(html,/id="backMeaning"/,'back translation element missing');
assert.match(html,/id="sentenceToggle"/,'sentence toggle missing');
assert.match(html,/id="sentencePanel"[^>]*hidden/,'sentence panel must be collapsed by default');
assert.match(html,/id="wordMeaning"[^>]*hidden/,'front-face translation must stay hidden');
assert.match(read('js/app.js'),/sentenceExpanded:false/,'sentence state missing');
assert.match(read('js/app.js'),/backMeaningNote/,'translation note binding missing');
assert.equal(words.length,954,'unexpected vocabulary size');
assert.equal(new Set(words.map(w=>w.id)).size,words.length,'duplicate word ids');
for(const w of words){assert.ok(typeof w.ukrainian==='string'&&w.ukrainian.trim(),'missing Ukrainian translation');assert.ok('translationNote' in w,'translationNote field missing')}
const centrum=words.find(w=>w.german==='das Stadtzentrum');
assert.equal(centrum?.pluralForm,'Stadtzentren','plural reconstruction regression');

for(const asset of [...sw.matchAll(/'([^']+)'/g)].map(m=>m[1]).filter(x=>x.startsWith('./'))){assert.ok(fs.existsSync(path.join(root,asset))||asset==='./','missing SW asset '+asset)}
const srcs=[...new Set(words.map(w=>w.source))];assert.equal(srcs.length,7,'expected seven lesson source groups');
console.log('SMOKE OK');
