import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(new URL('..',import.meta.url).pathname);
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const html=read('index.html');
const js=read('js/app.js');
const server=read('server/index.mjs');
const words=JSON.parse(read('data/words.json'));
const manifest=JSON.parse(read('data/book-vocabulary-manifest.json'));
assert.ok(Array.isArray(words)&&words.length>=900,'book vocabulary is incomplete');
assert.deepEqual(new Set(words.map(w=>w.topicNumber)),new Set([8,9,10,11,12,13,14]),'lessons 8-14 are not the whole bundled range');
assert.equal(words[0].topicNumber,8,'dataset must start at lesson 8');
assert.ok(words[0].german.includes('Witwer'),'lesson 8 order is not preserved');
assert.ok(words.some(w=>w.german==='schulpflichtig'),'end-of-book vocabulary missing');
assert.ok(words.every(w=>w.german&&w.ukrainian&&w.emoji&&w.sentence&&w.sentenceUa&&w.phonetic&&w.topicId&&w.sourcePage&&w.headword!==undefined&&w.pluralForm!==undefined),'word record missing required study/source fields');
assert.ok(words.every(w=>! /\(Sg\.?\)/i.test(w.headword)),'Sg marker leaked into headword');
assert.ok(words.every(w=>! /\(Sg\.?\)/i.test(w.phonetic)),'Sg marker leaked into phonetic');
assert.ok(words.every(w=>w.topicNumber>=8&&w.topicNumber<=14),'vocabulary outside lesson 8-14 present');
assert.equal(new Set(words.map(w=>w.id)).size,words.length,'duplicate word ids remain');
assert.ok(words.every(w=>String(w.german).trim()===String(w.headword).trim()),'display German field must match clean headword');
assert.ok(words.every(w=>!/[\(]Sg\.?[\)]|¨-|,\s*-|[\(]Pl\.?[\)]/i.test(String(w.german))), 'dictionary markers leaked into display German');
assert.equal(words.filter(w=>w.topicNumber===8 && w.emoji).length, manifest.byLesson['8'],'topic 8 emoji coverage incomplete');
assert.equal(words.filter(w=>w.topicNumber===14).length, manifest.byLesson['14'],'topic 14 count mismatch');
assert.doesNotMatch(html,/Random Dice|Battle Board|START WAVE|enemy|boss|spawnDie|autoMerge/i,'old game UI still present');
assert.doesNotMatch(js,/diceTypes|startWave|spawnDie|autoMerge|battleQuestion|Random Dice/i,'old game logic still present');
assert.ok(html.includes('id="flashcard"'),'flashcard missing');
assert.ok(html.includes('id="rememberBtn"')&&html.includes('id="forgotBtn"'),'two-action controls missing');
assert.ok(html.includes('id="speakWord"')&&html.includes('id="speakSentence"'),'audio controls missing');
assert.ok(js.includes('speechSynthesis'),'speech synthesis missing');
assert.ok(js.includes('intervalForQuality')&&js.includes('mastery'),'SRS/mastery missing');
assert.ok(js.includes('const disabled=state.answerLock||!state.flipped'),'answer buttons must stay locked before reveal');
assert.ok(js.includes('state.flipped&&!state.answerLock'),'swipe answers must stay locked before reveal');
assert.ok(js.includes("if(mode==='review')"),'review mode must retain dedicated SRS selection');
assert.ok(!js.includes('const originalPickSession'),'pickSession must not be overridden after boot');
assert.ok(js.includes('phoneticSource') || js.includes('phonetic(w.phonetic'),'phonetic rendering missing');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);
const dup=ids.filter((id,i)=>ids.indexOf(id)!==i);assert.equal(new Set(dup).size,0,'duplicate ids: '+[...new Set(dup)].join(', '));
const refIds=[...js.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);
for(const id of new Set(refIds))assert.ok(ids.includes(id),'missing DOM id: '+id);
const css=read('css/main.css');
assert.match(css,/\.flashcard\.is-flipped \.flash-front\{transform:rotateY\(-180deg\)/,'flip front fix missing');
assert.match(css,/\.flashcard\.is-flipped \.flash-back\{transform:rotateY\(0deg\)/,'flip back fix missing');
assert.match(css,/\.flash-face\{[^}]*backface-visibility:hidden/,'backface visibility missing');
assert.equal(read('VERSION').trim(),'0.023','version file mismatch');
assert.equal(JSON.parse(read('package.json')).version,'0.0.23','package version mismatch');
assert.match(read('server/index.mjs'),/VERSION='0.023'/,'server version mismatch');
assert.match(read('sw.js'),/gestalt-v0\.023/,'service worker cache version mismatch');
const sw=read('sw.js');for(const asset of [...sw.matchAll(/'([^']+)'/g)].map(m=>m[1]).filter(x=>x.startsWith('./'))){assert.ok(fs.existsSync(path.join(root,asset))||asset==='./','missing SW asset '+asset)}
const srcs=[...new Set(words.map(w=>w.source))];assert.equal(srcs.length,7,'expected seven lesson source groups');
console.log('SMOKE OK');
