import {TelegramBridge} from '../telegram/TelegramBridge.js';
export class WordTrial{
 constructor(words,state,onComplete){this.words=words;this.state=state;this.onComplete=onComplete;this.i=0;this.earnedXP={};this.questions=this.makeQuestions();}
 makeQuestions(){const pool=[...this.words].sort(()=>Math.random()-.5);return pool.slice(0,Math.min(5,pool.length)).map(correct=>{const others=this.words.filter(w=>w.id!==correct.id).sort(()=>Math.random()-.5).slice(0,3);return{wordObj:correct,options:[correct,...others].sort(()=>Math.random()-.5).map(w=>w.translation),correct:correct.translation}})}
 speak(text){if(!this.state.settings.sound||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='de-DE';u.rate=.88;window.speechSynthesis.speak(u)}
 render(el){if(this.i>=this.questions.length)return this.finish(el);const q=this.questions[this.i];this.speak(q.wordObj.word);el.innerHTML=`<div class="trial-wrap"><div class="topbar" style="margin:-20px -16px 0"><button id="trial-back" class="btn-secondary" style="padding:7px 10px">←</button><h2>🧪 Word Trial</h2><span>${this.i+1}/${this.questions.length}</span></div><div class="trial-word">${q.wordObj.emoji} ${q.wordObj.word}</div><div class="trial-trans">Що означає це слово? <button id="speak" class="btn-secondary" style="padding:4px 8px">🔊</button></div><div class="options">${q.options.map((x,n)=>`<button class="btn-secondary option-btn" data-i="${n}">${x}</button>`).join('')}</div><div id="feedback" class="feedback"></div><p class="subtitle">Правильна відповідь дає +120 XP картці.</p></div>`;
 el.querySelector('#speak').onclick=()=>this.speak(q.wordObj.word);el.querySelector('#trial-back').onclick=()=>this.finish(el);
 el.querySelectorAll('.option-btn').forEach(b=>b.onclick=()=>{if(b.disabled)return;el.querySelectorAll('.option-btn').forEach(x=>x.disabled=true);const ok=b.textContent===q.correct;b.style.background=ok?'#10b981':'#ef4444';b.style.color='#fff';el.querySelector('#feedback').textContent=ok?'✓ Правильно! +120 XP':'✕ Правильна відповідь: '+q.correct;TelegramBridge.haptic(ok?'success':'error');if(ok)this.earnedXP[q.wordObj.id]=(this.earnedXP[q.wordObj.id]||0)+120;setTimeout(()=>{this.i++;this.render(el)},650)})}
 finish(el){el.innerHTML='';this.onComplete(this.earnedXP)}
}